#!/bin/bash

# Setup Development Environment Script
# This script creates the necessary .env files with generated secrets

set -e

echo "🚀 Setting up OmniTrackr Development Environment..."
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to generate random hex string (64 chars for AES-256)
generate_key() {
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
}

# Function to generate random password
generate_password() {
    node -e "console.log(require('crypto').randomBytes(16).toString('base64').replace(/[^a-zA-Z0-9]/g, '').substring(0, 20))"
}

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed. Please install Node.js 20+ first.${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js is installed"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}⚠${NC}  Docker is not installed. You'll need it to run local databases."
    echo "   Install from: https://www.docker.com/get-started"
    exit 1
else
    echo -e "${GREEN}✓${NC} Docker is installed"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 1: Creating Docker environment file"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create Docker .env file
DOCKER_ENV_FILE="infrastructure/docker/.env"
if [ -f "$DOCKER_ENV_FILE" ]; then
    echo -e "${YELLOW}⚠${NC}  $DOCKER_ENV_FILE already exists."
    read -p "   Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Skipping Docker .env creation..."
    else
        rm "$DOCKER_ENV_FILE"
    fi
fi

if [ ! -f "$DOCKER_ENV_FILE" ]; then
    echo "Creating $DOCKER_ENV_FILE..."

    DEV_DB_PASSWORD=$(generate_password)
    TEST_DB_PASSWORD=$(generate_password)
    PGADMIN_PASSWORD=$(generate_password)

    cat > "$DOCKER_ENV_FILE" <<EOF
# Docker Compose Environment Variables
# Auto-generated by setup-dev-env.sh
# NEVER COMMIT THIS FILE!

# PostgreSQL Development
POSTGRES_DEV_DB=omnitrackr_dev
POSTGRES_DEV_USER=dev_user
POSTGRES_DEV_PASSWORD=${DEV_DB_PASSWORD}
POSTGRES_DEV_PORT=5432

# PostgreSQL Test
POSTGRES_TEST_DB=omnitrackr_test
POSTGRES_TEST_USER=test_user
POSTGRES_TEST_PASSWORD=${TEST_DB_PASSWORD}
POSTGRES_TEST_PORT=5433

# PgAdmin (optional)
PGADMIN_EMAIL=admin@omnitrackr.local
PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
PGADMIN_PORT=5050
EOF

    echo -e "${GREEN}✓${NC} Created $DOCKER_ENV_FILE"
    echo ""
    echo -e "${BLUE}📝 Database credentials:${NC}"
    echo "   Dev DB Password:  ${DEV_DB_PASSWORD}"
    echo "   Test DB Password: ${TEST_DB_PASSWORD}"
    echo ""
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 2: Creating API environment files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Read DB passwords from Docker .env
source "$DOCKER_ENV_FILE"

# Create .env.development.local for API
ENV_DEV_FILE="packages/api/.env.development.local"
if [ -f "$ENV_DEV_FILE" ]; then
    echo -e "${YELLOW}⚠${NC}  $ENV_DEV_FILE already exists."
    read -p "   Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Skipping..."
    else
        rm "$ENV_DEV_FILE"
    fi
fi

if [ ! -f "$ENV_DEV_FILE" ]; then
    echo "Creating $ENV_DEV_FILE..."

    ENCRYPTION_KEY=$(generate_key)
    JWT_SECRET=$(generate_key)

    cat > "$ENV_DEV_FILE" <<EOF
# Development Local Environment - NEVER COMMIT THIS FILE!
# Auto-generated by setup-dev-env.sh

# Database Credentials (must match Docker .env)
DB_USER=${POSTGRES_DEV_USER}
DB_PASSWORD=${POSTGRES_DEV_PASSWORD}

# Encryption Master Key (AES-256)
ENCRYPTION_MASTER_KEY=${ENCRYPTION_KEY}

# JWT Secret
JWT_SECRET=${JWT_SECRET}
EOF

    echo -e "${GREEN}✓${NC} Created $ENV_DEV_FILE"
fi

# Create .env.test.local for API
ENV_TEST_FILE="packages/api/.env.test.local"
if [ -f "$ENV_TEST_FILE" ]; then
    echo -e "${YELLOW}⚠${NC}  $ENV_TEST_FILE already exists."
    read -p "   Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Skipping..."
    else
        rm "$ENV_TEST_FILE"
    fi
fi

if [ ! -f "$ENV_TEST_FILE" ]; then
    echo "Creating $ENV_TEST_FILE..."

    ENCRYPTION_KEY_TEST=$(generate_key)
    JWT_SECRET_TEST=$(generate_key)

    cat > "$ENV_TEST_FILE" <<EOF
# Test Local Environment - NEVER COMMIT THIS FILE!
# Auto-generated by setup-dev-env.sh

# Database Credentials (must match Docker .env)
DB_USER=${POSTGRES_TEST_USER}
DB_PASSWORD=${POSTGRES_TEST_PASSWORD}

# Encryption Master Key (AES-256)
ENCRYPTION_MASTER_KEY=${ENCRYPTION_KEY_TEST}

# JWT Secret
JWT_SECRET=${JWT_SECRET_TEST}
EOF

    echo -e "${GREEN}✓${NC} Created $ENV_TEST_FILE"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 3: Starting Docker containers"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

cd infrastructure/docker

# Check if containers are already running
if docker compose ps | grep -q "omnitrackr-postgres-dev.*running"; then
    echo -e "${YELLOW}⚠${NC}  Docker containers already running."
    read -p "   Restart them? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Stopping containers..."
        docker compose down
        echo "Starting containers..."
        docker compose up -d postgres-dev postgres-test
    fi
else
    echo "Starting Docker containers..."
    docker compose up -d postgres-dev postgres-test
fi

echo ""
echo "⏳ Waiting for databases to be ready..."
sleep 5

# Check health
MAX_RETRIES=30
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose ps | grep -q "healthy"; then
        echo -e "${GREEN}✓${NC} Databases are healthy and ready!"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "   Waiting... ($RETRY_COUNT/$MAX_RETRIES)"
    sleep 2
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}❌ Databases failed to become healthy. Check logs with: docker compose logs${NC}"
    exit 1
fi

cd ../..

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 4: Installing dependencies"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

npm install

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 5: Running database migrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Run migrations for development
echo "Running migrations for development database..."
NODE_ENV=development npm run db:migrate --workspace=packages/api

echo ""

# Run migrations for test
echo "Running migrations for test database..."
NODE_ENV=test npm run db:migrate --workspace=packages/api

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ Development environment setup complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Next steps:"
echo ""
echo "  1. Start the API server:"
echo "     ${YELLOW}npm run dev:api${NC}"
echo ""
echo "  2. Run tests:"
echo "     ${YELLOW}npm test --workspace=packages/api${NC}"
echo ""
echo "  3. Access PgAdmin (optional):"
echo "     ${YELLOW}cd infrastructure/docker && docker compose --profile tools up -d pgadmin${NC}"
echo "     Then open: ${BLUE}http://localhost:5050${NC}"
echo ""
echo "  4. View database logs:"
echo "     ${YELLOW}cd infrastructure/docker && docker compose logs -f postgres-dev${NC}"
echo ""
echo "  5. Stop databases:"
echo "     ${YELLOW}cd infrastructure/docker && docker compose down${NC}"
echo ""
echo "  6. Connect to development database:"
echo "     ${YELLOW}psql -h localhost -p 5432 -U dev_user -d omnitrackr_dev${NC}"
echo ""
echo "Happy coding! 🚀"
echo ""
